### ISSUE TITLE
Is it compatible with latest ES 1.5.0?

### ISSUE THREAD

**Issue by teebu** [kzwang/elasticsearch-river-dynamodb#2]
I can't seem to get it started.

**Comment by teebu** [comment]
```
Exception in thread "elasticsearch[Slither][dynamodb_river][T#1]" com.amazonaws.AmazonClientException: Unable to marshall request to JSON: N
ull key.
        at com.amazonaws.services.dynamodbv2.model.transform.ScanRequestMarshaller.marshall(ScanRequestMarshaller.java:265)
        at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.scan(AmazonDynamoDBClient.java:291)
        at org.elasticsearch.river.dynamodb.DynamoDbRiver$Indexer.index(DynamoDbRiver.java:217)
        at org.elasticsearch.river.dynamodb.DynamoDbRiver$Indexer.run(DynamoDbRiver.java:187)
        at java.lang.Thread.run(Unknown Source)
Caused by: com.amazonaws.util.json.JSONException: Null key.
        at com.amazonaws.util.json.JSONWriter.key(JSONWriter.java:206)
        at com.amazonaws.services.dynamodbv2.model.transform.ScanRequestMarshaller.marshall(ScanRequestMarshaller.java:107)
        ... 4 more
```

**Comment by teebu** [comment]
I figured out the null key error. It had to do with the "updated" field. that field has to be a number in the database. 

I have another problem now. The plugin just makes ES unresponsive, this is the last line in the log: 

```
[2015-04-09 03:01:04,445][INFO ][river.dynamodb           ] [elasticsearch1.localdomain] [dynamodb][votes] Start DynamoDB for table Votes
```

I managed to get this river plugin working on my windows machine, but the Linux is giving me trouble.
